version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    #entrypoint: ./entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: psql
    build: ./databaseDefault
    ports:
      - "5432"
    #volumes:
    #  - ./back/db/scriptProyecto.sql:/docker-entrypoint.initdb.d/db.sql
    environment:
      POSTGRES_DB: novaDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: novaSecret
