# Generated by Django 2.2.3 on 2019-07-07 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('pkBodega', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('pkCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('pknit', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=128)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('pkSubCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreSubCategoria', models.CharField(max_length=256)),
                ('fkCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('pkProducto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1024)),
                ('iva', models.FloatField()),
                ('precio', models.IntegerField()),
                ('rutaImagen', models.ImageField(default='..productosImagenes/no-img.jpg', upload_to='../productosImagenes')),
                ('fkSubCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.SubCategoria')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=64)),
                ('cantidad', models.IntegerField()),
                ('fkBodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega')),
                ('fkProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Proveedor')),
            ],
        ),
    ]
