# Generated by Django 2.2.3 on 2019-07-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('BOG', 'Bogotá'), ('IBG', 'Ibague'), ('SOL', 'Soledad'), ('SOAC', 'Soacha'), ('B/Q', 'Barranquilla'), ('CUC', 'Cucuta'), ('CART', 'Cartagena'), ('BCM', 'Bucaramanga'), ('MED', 'Medellín'), ('CALI', 'Cali')], max_length=4),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pknit',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
