# Generated by Django 2.2.3 on 2019-07-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20190708_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('IBG', 'Ibague'), ('CART', 'Cartagena'), ('BCM', 'Bucaramanga'), ('SOL', 'Soledad'), ('CALI', 'Cali'), ('BOG', 'Bogotá'), ('B/Q', 'Barranquilla'), ('CUC', 'Cucuta'), ('SOAC', 'Soacha'), ('MED', 'Medellín')], max_length=4),
        ),
    ]
