# Generated by Django 2.2.3 on 2019-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20190708_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('SOL', 'Soledad'), ('BOG', 'Bogotá'), ('SOAC', 'Soacha'), ('MED', 'Medellín'), ('CART', 'Cartagena'), ('B/Q', 'Barranquilla'), ('CUC', 'Cucuta'), ('CALI', 'Cali'), ('BCM', 'Bucaramanga'), ('IBG', 'Ibague')], default='CALI', max_length=4),
        ),
    ]
