# Generated by Django 2.2.3 on 2019-07-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20190708_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('SOL', 'Soledad'), ('CART', 'Cartagena'), ('CUC', 'Cucuta'), ('BOG', 'Bogotá'), ('MED', 'Medellín'), ('BCM', 'Bucaramanga'), ('IBG', 'Ibague'), ('SOAC', 'Soacha'), ('CALI', 'Cali'), ('B/Q', 'Barranquilla')], default='CALI', max_length=4),
        ),
    ]
