# Generated by Django 2.2.3 on 2019-07-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20190708_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(choices=[('SOAC', 'Soacha'), ('SOL', 'Soledad'), ('B/Q', 'Barranquilla'), ('MED', 'Medellín'), ('IBG', 'Ibague'), ('BCM', 'Bucaramanga'), ('CALI', 'Cali'), ('CUC', 'Cucuta'), ('BOG', 'Bogotá'), ('CART', 'Cartagena')], default='CALI', max_length=4),
        ),
    ]
