# Generated by Django 2.2.3 on 2019-07-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorDuenio',
            fields=[
                ('pkAdministradorDuenio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=8)),
                ('clave', models.CharField(editable=False, max_length=16)),
                ('tipo', models.CharField(choices=[('CEO', 'Duenio'), ('ADMIN', 'Administrador')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pkCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=16)),
                ('clave', models.CharField(editable=False, max_length=16)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=32)),
                ('telefono', models.IntegerField()),
                ('tipoDocumento', models.CharField(choices=[('PAS', 'Pasaporte'), ('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad')], max_length=1)),
                ('numeroDocumento', models.IntegerField()),
            ],
        ),
    ]
