# Generated by Django 2.2.3 on 2019-07-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradorduenio',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CEO', 'Duenio')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocumento',
            field=models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('PAS', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], max_length=1),
        ),
    ]
