# Generated by Django 2.2.3 on 2019-07-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190707_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocumento',
            field=models.CharField(choices=[('PAS', 'Pasaporte'), ('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadania')], max_length=1),
        ),
    ]
