# Generated by Django 2.2.3 on 2019-07-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190707_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradorduenio',
            name='tipo',
            field=models.CharField(choices=[('CEO', 'Duenio'), ('ADMIN', 'Administrador')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocumento',
            field=models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadania'), ('PAS', 'Pasaporte')], max_length=3),
        ),
    ]
