# Generated by Django 2.2.3 on 2019-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20190708_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocumento',
            field=models.CharField(choices=[('PAS', 'Pasaporte'), ('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad')], max_length=3),
        ),
    ]
