# Generated by Django 2.2.3 on 2019-07-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20190708_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradorduenio',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CEO', 'Duenio')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocumento',
            field=models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadania'), ('PAS', 'Pasaporte')], max_length=3),
        ),
    ]
