# Generated by Django 2.2.3 on 2019-07-07 05:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('pkFactura', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PagosDebito',
            fields=[
                ('pkPagosDebito', models.AutoField(primary_key=True, serialize=False)),
                ('numeroTarjetaDebito', models.IntegerField()),
                ('numeroPago', models.IntegerField()),
                ('ahorros', models.BooleanField()),
                ('porcentajePago', models.FloatField()),
                ('fkFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='PagosCredito',
            fields=[
                ('pkPagosCredito', models.AutoField(primary_key=True, serialize=False)),
                ('numeroAprobacion', models.IntegerField()),
                ('fechaAprobacion', models.DateField()),
                ('entidadAprobacion', models.CharField(choices=[('VI', 'VISA'), ('AX', 'AMERICANEXPRESS'), ('CA', 'MASTERCARD')], max_length=1)),
                ('porcentajePago', models.FloatField()),
                ('fkFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('fkFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Factura')),
                ('fkProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoSubCategoria',
            fields=[
                ('pkDescuentoSubCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(default=django.utils.timezone.now)),
                ('fechaFin', models.DateField()),
                ('porcentajeDescuento', models.FloatField()),
                ('fkSubCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.SubCategoria')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoProducto',
            fields=[
                ('pkDescuentoProducto', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(default=django.utils.timezone.now)),
                ('fechaFin', models.DateField()),
                ('porcentajeDescuento', models.FloatField()),
                ('fkProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoCategoria',
            fields=[
                ('pkDescuentoCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(default=django.utils.timezone.now)),
                ('fechaFin', models.DateField()),
                ('porcentajeDescuento', models.FloatField()),
                ('fkCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Categoria')),
            ],
        ),
    ]
