# Generated by Django 2.2.3 on 2019-07-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20190707_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoscredito',
            name='entidadAprobacion',
            field=models.CharField(choices=[('CA', 'MASTERCARD'), ('AX', 'AMERICANEXPRESS'), ('VI', 'VISA')], max_length=1),
        ),
    ]
