# Generated by Django 2.2.3 on 2019-07-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20190707_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoscredito',
            name='entidadAprobacion',
            field=models.CharField(choices=[('AX', 'AMERICANEXPRESS'), ('CA', 'MASTERCARD'), ('VI', 'VISA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pagoscredito',
            name='numeroAprobacion',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pagosdebito',
            name='numeroPago',
            field=models.CharField(max_length=4),
        ),
    ]
