# Generated by Django 2.2.3 on 2019-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20190708_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentocategoria',
            name='porcentajeDescuento',
            field=models.FloatField(max_length=99),
        ),
        migrations.AlterField(
            model_name='pagoscredito',
            name='entidadAprobacion',
            field=models.CharField(choices=[('AX', 'AMERICANEXPRESS'), ('CA', 'MASTERCARD'), ('VI', 'VISA')], max_length=2),
        ),
    ]
