# Generated by Django 2.2.3 on 2019-07-08 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20190708_2204'),
        ('ventas', '0007_auto_20190708_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='nombreCliente',
        ),
        migrations.AddField(
            model_name='factura',
            name='fkCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagoscredito',
            name='entidadAprobacion',
            field=models.CharField(choices=[('CA', 'MASTERCARD'), ('AX', 'AMERICANEXPRESS'), ('VI', 'VISA')], max_length=2),
        ),
    ]
