# Generated by Django 2.2.3 on 2019-07-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20190708_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoscredito',
            name='entidadAprobacion',
            field=models.CharField(choices=[('AX', 'AMERICANEXPRESS'), ('VI', 'VISA'), ('CA', 'MASTERCARD')], max_length=2),
        ),
    ]
